### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these LGTM [code quality badges](https://lgtm.com/projects/g/ultravideo/kvazaar/ci/#badges) to your project. They indicate how you care about code quality and encourage your future contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/ultravideo/kvazaar).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by friedrichschoene** [comment]
is is clearly spam

**Comment by xcorail** [comment]
Hi @friedrichschoene 

Sorry that it felt like it ... No it's not a spam, I am a real human person, asking for feedback on LGTM. 
However I agree that this was not solicited, so if it's annoying for you, please accept my apologies and  just close the PR.

Cheers

**Comment by friedrichschoene** [comment]
Spam also qualifies as spam if created by a real person.

**Comment by fador** [comment]
Thank you for the pull request, but I don't think we want any extra badges right now.

The "alerts" we see for Kvazaar in LGTM.com are not critical and mostly covered by limiting the input values. I'm seeing too many unrelevant alerts right now to figure out if there is anything actually wrong, but interesting service anyway ;)

**Comment by xcorail** [comment]
Hi @fador 
Thanks for the feedback. Much appreciated.

> The "alerts" we see for Kvazaar in LGTM.com are not critical 

Indeed, your project has no "Error", only "Warnings" and "Recommendations"

> I'm seeing too many unrelevant alerts right now

I understand. What our users do in this case, where the current backlog only has no critical alerts, is that they don't waste time with these old alerts, but they make sure to catch new ones. They integrate LGTM in their Pull Requests, to analyse the PRs and report new problems in the comments. It's a [one click operation](https://lgtm.com/projects/g/ultravideo/kvazaar/ci/)

>  interesting service anyway ;)

Thanks for this. Note that this service is free for public projects, so the alerts and the PR integration will always be there for you, even without the badges ;) 

Cheers and best of luck for kvazaar

**Pull request closed without merging**
